services:
  tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    entrypoint: []
    working_dir: /app
    volumes:
      - .:/app
    command: /opt/dr-stone-venv/bin/python -m pytest
