import type { SearchRunResult, SearchResultItem } from "@dr-stone/database";
import type { BrowserContext, Page } from "playwright";

import { buildBrowserLaunchOptions, createStealthBrowserContext } from "../../browser/playwright.js";
import { FetchError } from "../../errors.js";
import type { LoggerLike, ScrapperSettings, SearchSource } from "../../types.js";
import {
  buildMercadoLivreSearchUrl,
  MERCADO_LIVRE_SEARCH_BASE_URL,
  parseMercadoLivreListingCandidates,
  type MercadoLivreListingCandidate
} from "./mercadolivre-parsing.js";

interface MercadoLivrePageExtraction {
  finalUrl: string;
  pageTitle: string;
  bodyTextSnippet: string;
  candidateCount: number;
  pageNumbers: number[];
  nextPageUrl: string | null;
  candidates: MercadoLivreListingCandidate[];
}

interface MercadoLivrePageDiagnostics {
  responseStatus: number | null;
  finalUrl: string | null;
  pageTitle: string | null;
  bodyTextSnippet: string | null;
  candidateCount: number;
  itemCount: number;
  totalPages: number;
  nextPageDetected: boolean;
  challengeDetected: boolean;
  cloudflareDetected: boolean;
  cloudfrontDetected: boolean;
  captchaDetected: boolean;
  accessDeniedDetected: boolean;
  accountVerificationDetected: boolean;
  emptyResultsDetected: boolean;
}

interface MercadoLivreSearchPage {
  finalUrl: string;
  nextPageUrl: string | null;
  items: SearchResultItem[];
  diagnostics: MercadoLivrePageDiagnostics;
}

interface MercadoLivreSearchAttempt {
  attemptNumber: number;
  maxAttempts: number;
  proxySessionId: string | null;
}

export interface MercadoLivreChallengeSignals {
  challengeDetected: boolean;
  cloudflareDetected: boolean;
  cloudfrontDetected: boolean;
  captchaDetected: boolean;
  accessDeniedDetected: boolean;
  accountVerificationDetected: boolean;
}

const MAX_PAGE_VISITS = 20;
const MAX_SEARCH_ATTEMPTS = 3;
const PAGE_NAVIGATION_TIMEOUT_MS = 45_000;

export function detectMercadoLivreChallengeSignals(input: {
  finalUrl?: string | null;
  pageTitle?: string | null;
  bodyTextSnippet?: string | null;
}): MercadoLivreChallengeSignals {
  const finalUrl = input.finalUrl?.toLocaleLowerCase() ?? "";
  const pageTitle = input.pageTitle?.toLocaleLowerCase() ?? "";
  const bodyText = input.bodyTextSnippet?.toLocaleLowerCase() ?? "";
  const cloudflareDetected = /cloudflare|cf-chl|challenge-platform/.test(bodyText);
  const cloudfrontDetected =
    /cloudfront|request blocked|generated by cloudfront/.test(bodyText) ||
    /cloudfront|request blocked|generated by cloudfront/.test(pageTitle);
  const captchaDetected =
    /captcha|sou humano|verify you are human|verifique se você é humano/.test(bodyText) ||
    /captcha|verify you are human|verifique se você é humano/.test(pageTitle);
  const accessDeniedDetected =
    /access denied|403 forbidden|403 error|request blocked/.test(bodyText) ||
    /access denied|403 forbidden|403 error/.test(pageTitle);
  const accountVerificationDetected =
    finalUrl.includes("/gz/account-verification") ||
    /para continuar,\s*acesse sua conta|já tenho conta|sou novo|account verification/.test(
      bodyText
    ) ||
    /account verification|acesse sua conta/.test(pageTitle);

  return {
    challengeDetected:
      cloudflareDetected ||
      cloudfrontDetected ||
      captchaDetected ||
      accessDeniedDetected ||
      accountVerificationDetected,
    cloudflareDetected,
    cloudfrontDetected,
    captchaDetected,
    accessDeniedDetected,
    accountVerificationDetected
  };
}

export class MercadoLivreSource implements SearchSource {
  readonly sourceName = "mercadolivre";
  readonly strategy = "browser" as const;

  constructor(
    private readonly settings: Pick<
      ScrapperSettings,
      "proxyServer" | "proxyUsername" | "proxyPassword" | "userAgent"
    >,
    private readonly logger: LoggerLike
  ) {}

  buildSearchUrl(searchTerm: string): string {
    return buildMercadoLivreSearchUrl(searchTerm);
  }

  async search(searchTerm: string): Promise<SearchRunResult> {
    const maxAttempts = this.settings.proxyServer ? MAX_SEARCH_ATTEMPTS : 1;
    let lastError: FetchError | null = null;

    for (let attemptNumber = 1; attemptNumber <= maxAttempts; attemptNumber += 1) {
      const attempt = this.buildSearchAttempt(searchTerm, attemptNumber, maxAttempts);

      try {
        return await this.searchOnce(searchTerm, attempt);
      } catch (error) {
        const fetchError =
          error instanceof FetchError
            ? error
            : new FetchError(
                `Mercado Livre search attempt ${attempt.attemptNumber} failed unexpectedly`,
                {
                  code: "mercadolivre_search_failed",
                  retriable: true,
                  url: this.buildSearchUrl(searchTerm),
                  details: {
                    attemptNumber: attempt.attemptNumber,
                    maxAttempts: attempt.maxAttempts,
                    proxySessionId: attempt.proxySessionId,
                    originalErrorType:
                      error instanceof Error ? error.constructor.name : "UnknownError",
                    originalErrorMessage: error instanceof Error ? error.message : String(error)
                  }
                }
              );
        lastError = fetchError;

        if (!this.shouldRetryAttempt(fetchError, attempt)) {
          throw fetchError;
        }

        this.logger.warn(
          {
            event: "search_source_retry_scheduled",
            source: this.sourceName,
            searchTerm,
            attemptNumber: attempt.attemptNumber,
            maxAttempts: attempt.maxAttempts,
            errorCode: fetchError.code,
            responseStatus: fetchError.statusCode ?? null,
            finalUrl: fetchError.finalUrl ?? null,
            proxySessionId: attempt.proxySessionId
          },
          "search_source_retry_scheduled"
        );
      }
    }

    throw lastError ?? new FetchError("Mercado Livre search failed without a recorded attempt error");
  }

  async close(): Promise<void> {}

  private buildSearchAttempt(
    searchTerm: string,
    attemptNumber: number,
    maxAttempts: number
  ): MercadoLivreSearchAttempt {
    return {
      attemptNumber,
      maxAttempts,
      proxySessionId: this.settings.proxyServer
        ? buildMercadoLivreProxySessionId(searchTerm, attemptNumber)
        : null
    };
  }

  private shouldRetryAttempt(
    error: FetchError,
    attempt: Pick<MercadoLivreSearchAttempt, "attemptNumber" | "maxAttempts">
  ): boolean {
    return (
      attempt.attemptNumber < attempt.maxAttempts &&
      error.retriable &&
      (
        error.code === "mercadolivre_challenge_detected" ||
        error.code === "mercadolivre_results_timeout" ||
        error.statusCode === 403
      )
    );
  }

  private async searchOnce(
    searchTerm: string,
    attempt: MercadoLivreSearchAttempt
  ): Promise<SearchRunResult> {
    const searchUrl = this.buildSearchUrl(searchTerm);
    const { chromium } = await import("playwright");
    const browser = await chromium.launch(
      buildBrowserLaunchOptions(this.settings, {
        proxySessionId: attempt.proxySessionId
      })
    );
    const context = await createStealthBrowserContext(browser, this.settings);
    let page: Page | null = null;
    let responseStatus: number | null = null;

    try {
      page = await this.createPage(context);
      const response = await page.goto(searchUrl, {
        waitUntil: "domcontentloaded",
        timeout: PAGE_NAVIGATION_TIMEOUT_MS
      });
      responseStatus = response?.status() ?? null;
      await this.settlePage(page);

      const firstPage = await this.extractPageWithListingWait(page, responseStatus);
      if (firstPage.items.length === 0) {
        throw this.buildEmptyPageError(searchTerm, searchUrl, firstPage.diagnostics, attempt);
      }

      const seenCanonicalUrls = new Set(firstPage.items.map((item) => item.canonicalUrl));
      const items = [...firstPage.items];
      const visitedUrls = new Set([normalizeVisitedUrl(firstPage.finalUrl)]);

      let nextPageUrl = firstPage.nextPageUrl;
      let pageCount = Math.max(1, firstPage.diagnostics.totalPages);
      let lastDiagnostics = firstPage.diagnostics;

      while (nextPageUrl && visitedUrls.size < MAX_PAGE_VISITS) {
        const normalizedNextPageUrl = normalizeVisitedUrl(nextPageUrl);
        if (visitedUrls.has(normalizedNextPageUrl)) {
          break;
        }

        visitedUrls.add(normalizedNextPageUrl);
        const paginatedResponse = await page.goto(nextPageUrl, {
          waitUntil: "domcontentloaded",
          timeout: PAGE_NAVIGATION_TIMEOUT_MS
        });
        await this.settlePage(page);

        const extractedPage = await this.extractPageWithListingWait(
          page,
          paginatedResponse?.status() ?? null,
          items.length
        );

        if (extractedPage.items.length === 0) {
          throw new FetchError(
            this.buildFailureMessage(
              extractedPage.diagnostics.challengeDetected
                ? "mercadolivre_challenge_detected"
                : "mercadolivre_empty_page",
              extractedPage.diagnostics
            ),
            {
              code: extractedPage.diagnostics.challengeDetected
                ? "mercadolivre_challenge_detected"
                : "mercadolivre_empty_page",
              retriable: true,
              statusCode: extractedPage.diagnostics.responseStatus ?? undefined,
              url: nextPageUrl,
              finalUrl: extractedPage.diagnostics.finalUrl ?? undefined,
              details: {
                pageNumber: visitedUrls.size,
                attemptNumber: attempt.attemptNumber,
                maxAttempts: attempt.maxAttempts,
                proxySessionId: attempt.proxySessionId,
                responseStatus: extractedPage.diagnostics.responseStatus,
                pageTitle: extractedPage.diagnostics.pageTitle,
                candidateCount: extractedPage.diagnostics.candidateCount,
                challengeDetected: extractedPage.diagnostics.challengeDetected,
                accountVerificationDetected: extractedPage.diagnostics.accountVerificationDetected,
                bodyTextSnippet: extractedPage.diagnostics.bodyTextSnippet
              }
            }
          );
        }

        for (const item of extractedPage.items) {
          if (seenCanonicalUrls.has(item.canonicalUrl)) {
            continue;
          }

          seenCanonicalUrls.add(item.canonicalUrl);
          items.push(item);
        }

        nextPageUrl = extractedPage.nextPageUrl;
        pageCount = Math.max(pageCount, extractedPage.diagnostics.totalPages, visitedUrls.size);
        lastDiagnostics = extractedPage.diagnostics;
      }

      const result: SearchRunResult = {
        source: this.sourceName,
        searchTerm,
        resolvedUrl: firstPage.finalUrl,
        totalResults: items.length,
        pageCount,
        items,
        fetchedAt: new Date().toISOString(),
        metadata: {
          searchUrl,
          responseStatus: firstPage.diagnostics.responseStatus,
          pageTitle: firstPage.diagnostics.pageTitle,
          candidateCount: firstPage.diagnostics.candidateCount,
          totalPages: pageCount,
          nextPageDetected: firstPage.diagnostics.nextPageDetected,
          challengeDetected: firstPage.diagnostics.challengeDetected,
          cloudflareDetected: firstPage.diagnostics.cloudflareDetected,
          cloudfrontDetected: firstPage.diagnostics.cloudfrontDetected,
          captchaDetected: firstPage.diagnostics.captchaDetected,
          accessDeniedDetected: firstPage.diagnostics.accessDeniedDetected,
          accountVerificationDetected: firstPage.diagnostics.accountVerificationDetected,
          emptyResultsDetected: firstPage.diagnostics.emptyResultsDetected,
          finalPageTitle: lastDiagnostics.pageTitle,
          proxyConfigured: Boolean(this.settings.proxyServer),
          attemptNumber: attempt.attemptNumber,
          maxAttempts: attempt.maxAttempts,
          proxySessionId: attempt.proxySessionId
        }
      };

      this.logger.info(
        {
          event: "search_scrape_succeeded",
          source: this.sourceName,
          searchTerm,
          resolvedUrl: result.resolvedUrl,
          totalResults: result.totalResults,
          pageCount: result.pageCount,
          itemCount: result.items.length,
          responseStatus: firstPage.diagnostics.responseStatus,
          pageTitle: firstPage.diagnostics.pageTitle,
          candidateCount: firstPage.diagnostics.candidateCount,
          challengeDetected: firstPage.diagnostics.challengeDetected,
          accountVerificationDetected: firstPage.diagnostics.accountVerificationDetected,
          proxyConfigured: Boolean(this.settings.proxyServer),
          attemptNumber: attempt.attemptNumber,
          proxySessionId: attempt.proxySessionId
        },
        "search_scrape_succeeded"
      );

      return result;
    } catch (error) {
      const diagnostics = page
        ? await this.collectDiagnostics(page, responseStatus)
        : this.buildFallbackDiagnostics(searchUrl, responseStatus);
      const errorCode =
        error instanceof Error && error.name === "TimeoutError"
          ? "mercadolivre_results_timeout"
          : diagnostics.challengeDetected
            ? "mercadolivre_challenge_detected"
            : "mercadolivre_search_failed";
      const fetchError =
        error instanceof FetchError
          ? error
          : new FetchError(this.buildFailureMessage(errorCode, diagnostics), {
              code: errorCode,
              retriable: true,
              statusCode: diagnostics.responseStatus ?? undefined,
              url: searchUrl,
              finalUrl: diagnostics.finalUrl ?? undefined,
              details: {
                searchTerm,
                attemptNumber: attempt.attemptNumber,
                maxAttempts: attempt.maxAttempts,
                proxySessionId: attempt.proxySessionId,
                responseStatus: diagnostics.responseStatus,
                finalUrl: diagnostics.finalUrl,
                pageTitle: diagnostics.pageTitle,
                candidateCount: diagnostics.candidateCount,
                itemCount: diagnostics.itemCount,
                totalPages: diagnostics.totalPages,
                nextPageDetected: diagnostics.nextPageDetected,
                challengeDetected: diagnostics.challengeDetected,
                cloudflareDetected: diagnostics.cloudflareDetected,
                cloudfrontDetected: diagnostics.cloudfrontDetected,
                captchaDetected: diagnostics.captchaDetected,
                accessDeniedDetected: diagnostics.accessDeniedDetected,
                accountVerificationDetected: diagnostics.accountVerificationDetected,
                emptyResultsDetected: diagnostics.emptyResultsDetected,
                bodyTextSnippet: diagnostics.bodyTextSnippet,
                proxyConfigured: Boolean(this.settings.proxyServer),
                originalErrorType: error instanceof Error ? error.constructor.name : "UnknownError",
                originalErrorMessage: error instanceof Error ? error.message : String(error)
              }
            });

      const shouldRetry = this.shouldRetryAttempt(fetchError, attempt);
      const logPayload = {
        event: "search_scrape_failed",
        source: this.sourceName,
        searchTerm,
        searchUrl,
        errorCode: fetchError.code,
        responseStatus: fetchError.statusCode ?? diagnostics.responseStatus,
        finalUrl: fetchError.finalUrl ?? diagnostics.finalUrl,
        pageTitle:
          typeof fetchError.details.pageTitle === "string"
            ? fetchError.details.pageTitle
            : diagnostics.pageTitle,
        candidateCount:
          typeof fetchError.details.candidateCount === "number"
            ? fetchError.details.candidateCount
            : diagnostics.candidateCount,
        challengeDetected:
          typeof fetchError.details.challengeDetected === "boolean"
            ? fetchError.details.challengeDetected
            : diagnostics.challengeDetected,
        accountVerificationDetected:
          typeof fetchError.details.accountVerificationDetected === "boolean"
            ? fetchError.details.accountVerificationDetected
            : diagnostics.accountVerificationDetected,
        bodyTextSnippet:
          typeof fetchError.details.bodyTextSnippet === "string"
            ? fetchError.details.bodyTextSnippet
            : diagnostics.bodyTextSnippet,
        proxyConfigured: Boolean(this.settings.proxyServer),
        attemptNumber: attempt.attemptNumber,
        maxAttempts: attempt.maxAttempts,
        proxySessionId: attempt.proxySessionId,
        originalErrorMessage:
          error instanceof Error && !(error instanceof FetchError) ? error.message : undefined
      };

      if (shouldRetry) {
        this.logger.warn(logPayload, "search_scrape_failed");
      } else {
        this.logger.error(logPayload, "search_scrape_failed");
      }

      throw fetchError;
    } finally {
      await context.close();
      await browser.close();
    }
  }

  private async createPage(context: BrowserContext): Promise<Page> {
    const page = await context.newPage();
    await this.blockChallengeScripts(page);
    return page;
  }

  private async blockChallengeScripts(page: Page): Promise<void> {
    await page.route("**/cdn-cgi/challenge-platform/**", (route) => route.abort());
  }

  private async settlePage(page: Page): Promise<void> {
    await this.safeRead(async () => {
      await page.waitForLoadState("networkidle", { timeout: 10_000 });
    });
    await page.waitForTimeout(3_000);
  }

  private async extractPage(
    page: Page,
    responseStatus: number | null,
    positionOffset = 0
  ): Promise<MercadoLivreSearchPage> {
    const extraction = await this.evaluatePage(page);
    const items = parseMercadoLivreListingCandidates(extraction.candidates, {
      baseUrl: MERCADO_LIVRE_SEARCH_BASE_URL,
      positionOffset
    });
    const diagnostics = this.buildDiagnostics(extraction, responseStatus, items.length);

    return {
      finalUrl: extraction.finalUrl,
      nextPageUrl: extraction.nextPageUrl,
      items,
      diagnostics
    };
  }

  private async extractPageWithListingWait(
    page: Page,
    responseStatus: number | null,
    positionOffset = 0
  ): Promise<MercadoLivreSearchPage> {
    let extractedPage = await this.extractPage(page, responseStatus, positionOffset);
    if (
      extractedPage.items.length > 0 ||
      responseStatus !== 200 ||
      extractedPage.diagnostics.challengeDetected
    ) {
      return extractedPage;
    }

    await this.waitForListingCandidates(page);
    extractedPage = await this.extractPage(page, responseStatus, positionOffset);
    return extractedPage;
  }

  private async evaluatePage(page: Page): Promise<MercadoLivrePageExtraction> {
    return page.evaluate((): MercadoLivrePageExtraction => {
      type DomNode = {
        href?: string | null;
        textContent?: string | null;
        innerText?: string | null;
        getAttribute?: (name: string) => string | null;
        querySelector?: (selector: string) => DomNode | null;
        querySelectorAll?: (selector: string) => Iterable<DomNode>;
      };
      const pageGlobals = globalThis as unknown as {
        document: {
          title: string;
          body: {
            innerText: string;
          };
          querySelector: (selector: string) => DomNode | null;
          querySelectorAll: (selector: string) => Iterable<DomNode>;
        };
        window: {
          location: {
            href: string;
          };
        };
      };
      const { document, window } = pageGlobals;

      const normalizeText = (value: string | null | undefined) =>
        value?.replace(/\s+/g, " ").trim() ?? "";

      const querySelectorAny = (
        root: {
          querySelector: (selector: string) => DomNode | null;
        },
        selectors: readonly string[]
      ): DomNode | null => {
        for (const selector of selectors) {
          const node = root.querySelector(selector);
          if (node) {
            return node;
          }
        }

        return null;
      };

      const listRoots = Array.from(
        document.querySelectorAll(
          "li.ui-search-layout__item, div.ui-search-result__wrapper, div[data-testid='result-item']"
        )
      );

      const candidates = listRoots.map((node) => {
        const element = node as DomNode & {
          textContent?: string | null;
          innerText?: string | null;
          getAttribute: (name: string) => string | null;
          querySelector: (selector: string) => DomNode | null;
        };

        const anchor = querySelectorAny(element, [
          "a.poly-component__title[href]",
          "a.ui-search-link[href]",
          "a[href*='/p/MLB']",
          "a[href*='MLB-']",
          "a[href]"
        ]) as
          | (DomNode & {
              href?: string | null;
              textContent?: string | null;
              getAttribute: (name: string) => string | null;
            })
          | null;

        const priceNode = querySelectorAny(element, [
          ".poly-price__current .andes-money-amount",
          ".poly-component__price .andes-money-amount",
          ".ui-search-price__second-line .andes-money-amount",
          ".andes-money-amount"
        ]) as
          | (DomNode & {
              textContent?: string | null;
              querySelector: (selector: string) => DomNode | null;
            })
          | null;

        const priceWholeNode = querySelectorAny(priceNode ?? element, [
          ".andes-money-amount__fraction"
        ]) as (DomNode & { textContent?: string | null }) | null;
        const priceCentsNode = querySelectorAny(priceNode ?? element, [
          ".andes-money-amount__cents"
        ]) as (DomNode & { textContent?: string | null }) | null;
        const currencyNode = querySelectorAny(priceNode ?? element, [
          ".andes-money-amount__currency-symbol"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const titleNode = querySelectorAny(element, [
          "a.poly-component__title",
          ".poly-component__title",
          "h2.ui-search-item__title",
          ".ui-search-item__title"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const sellerNode = querySelectorAny(element, [
          ".poly-component__seller",
          ".poly-component__seller .poly-component__seller-name",
          ".ui-search-official-store-label",
          "[class*='seller']"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const shippingNode = querySelectorAny(element, [
          ".poly-component__shipping",
          ".ui-search-item__shipping",
          "[class*='shipping']"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const installmentsNode = querySelectorAny(element, [
          ".poly-price__installments",
          ".ui-search-installments",
          "[class*='installments']"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const stockNode = querySelectorAny(element, [
          ".poly-component__available-quantity",
          "[class*='available']",
          "[class*='stock']"
        ]) as (DomNode & { textContent?: string | null }) | null;

        const listingTypeNode = querySelectorAny(element, [
          ".poly-component__status",
          ".ui-search-item__highlight-label",
          ".andes-badge",
          "[data-testid='listing-type']"
        ]) as (DomNode & { textContent?: string | null }) | null;

        return {
          href: anchor?.href ?? anchor?.getAttribute("href") ?? null,
          title: normalizeText(titleNode?.textContent),
          titleAttr: normalizeText(anchor?.getAttribute("title")),
          ariaLabel: normalizeText(anchor?.getAttribute("aria-label")),
          cardText: normalizeText(element.innerText ?? element.textContent),
          priceText: normalizeText(priceNode?.textContent),
          priceWhole: normalizeText(priceWholeNode?.textContent),
          priceCents: normalizeText(priceCentsNode?.textContent),
          currencyText: normalizeText(currencyNode?.textContent),
          sellerText: normalizeText(sellerNode?.textContent),
          shippingText: normalizeText(shippingNode?.textContent),
          installmentsText: normalizeText(installmentsNode?.textContent),
          stockText: normalizeText(stockNode?.textContent),
          listingType: normalizeText(listingTypeNode?.textContent),
          dataId:
            element.getAttribute("data-id") ??
            element.getAttribute("data-item-id") ??
            anchor?.getAttribute("data-id") ??
            null
        };
      });

      const nextLink = querySelectorAny(document, [
        "a.andes-pagination__link[title='Seguinte']",
        "a.andes-pagination__link[aria-label*='Seguinte']",
        "a.andes-pagination__link[aria-label*='Próxima']",
        "a[rel='next']",
        "a[title='Seguinte']",
        "a[aria-label*='Seguinte']",
        "a[aria-label*='Próxima']"
      ]) as (DomNode & { href?: string | null; getAttribute: (name: string) => string | null }) | null;

      const pageNumbers = Array.from(
        document.querySelectorAll(
          ".andes-pagination__button, .andes-pagination__link, nav[aria-label*='Paginação'] a, nav[aria-label*='Pagination'] a"
        )
      )
        .map((node) =>
          Number.parseInt(
            normalizeText((node as DomNode & { textContent?: string | null }).textContent),
            10
          )
        )
        .filter((value) => Number.isInteger(value) && value > 0);

      return {
        finalUrl: window.location.href,
        pageTitle: document.title,
        bodyTextSnippet: normalizeText(document.body.innerText).slice(0, 500),
        candidateCount: candidates.length,
        pageNumbers,
        nextPageUrl: nextLink?.href ?? nextLink?.getAttribute("href") ?? null,
        candidates
      };
    });
  }

  private buildDiagnostics(
    extraction: MercadoLivrePageExtraction,
    responseStatus: number | null,
    itemCount: number
  ): MercadoLivrePageDiagnostics {
    const pageTitle = extraction.pageTitle || null;
    const bodyText = extraction.bodyTextSnippet.toLocaleLowerCase();
    const challengeSignals = detectMercadoLivreChallengeSignals({
      finalUrl: extraction.finalUrl,
      pageTitle,
      bodyTextSnippet: extraction.bodyTextSnippet
    });

    return {
      responseStatus,
      finalUrl: extraction.finalUrl || null,
      pageTitle,
      bodyTextSnippet: extraction.bodyTextSnippet || null,
      candidateCount: extraction.candidateCount,
      itemCount,
      totalPages: Math.max(1, ...extraction.pageNumbers, itemCount > 0 ? 1 : 0),
      nextPageDetected: Boolean(extraction.nextPageUrl),
      challengeDetected: challengeSignals.challengeDetected,
      cloudflareDetected: challengeSignals.cloudflareDetected,
      cloudfrontDetected: challengeSignals.cloudfrontDetected,
      captchaDetected: challengeSignals.captchaDetected,
      accessDeniedDetected: challengeSignals.accessDeniedDetected,
      accountVerificationDetected: challengeSignals.accountVerificationDetected,
      emptyResultsDetected:
        itemCount === 0 &&
        /não há anúncios|não encontramos|sem resultados|resultados para/.test(bodyText)
    };
  }

  private buildEmptyPageError(
    searchTerm: string,
    searchUrl: string,
    diagnostics: MercadoLivrePageDiagnostics,
    attempt: MercadoLivreSearchAttempt
  ): FetchError {
    const errorCode = diagnostics.challengeDetected
      ? "mercadolivre_challenge_detected"
      : "mercadolivre_empty_page";

    return new FetchError(this.buildFailureMessage(errorCode, diagnostics), {
      code: errorCode,
      retriable: true,
      statusCode: diagnostics.responseStatus ?? undefined,
      url: searchUrl,
      finalUrl: diagnostics.finalUrl ?? undefined,
      details: {
        searchTerm,
        attemptNumber: attempt.attemptNumber,
        maxAttempts: attempt.maxAttempts,
        proxySessionId: attempt.proxySessionId,
        responseStatus: diagnostics.responseStatus,
        finalUrl: diagnostics.finalUrl,
        pageTitle: diagnostics.pageTitle,
        candidateCount: diagnostics.candidateCount,
        itemCount: diagnostics.itemCount,
        totalPages: diagnostics.totalPages,
        nextPageDetected: diagnostics.nextPageDetected,
        challengeDetected: diagnostics.challengeDetected,
        cloudflareDetected: diagnostics.cloudflareDetected,
        cloudfrontDetected: diagnostics.cloudfrontDetected,
        captchaDetected: diagnostics.captchaDetected,
        accessDeniedDetected: diagnostics.accessDeniedDetected,
        accountVerificationDetected: diagnostics.accountVerificationDetected,
        emptyResultsDetected: diagnostics.emptyResultsDetected,
        bodyTextSnippet: diagnostics.bodyTextSnippet,
        proxyConfigured: Boolean(this.settings.proxyServer)
      }
    });
  }

  private buildFailureMessage(
    errorCode: string,
    diagnostics: Pick<
      MercadoLivrePageDiagnostics,
      | "pageTitle"
      | "responseStatus"
      | "challengeDetected"
      | "accountVerificationDetected"
      | "emptyResultsDetected"
    > | null
  ): string {
    const reason =
      errorCode === "mercadolivre_results_timeout"
        ? "Mercado Livre listing results did not stabilize before the timeout"
        : errorCode === "mercadolivre_challenge_detected"
          ? "Mercado Livre challenge page remained active"
          : errorCode === "mercadolivre_empty_page"
            ? "Mercado Livre search page returned no extractable listing items"
            : "Mercado Livre search failed";

    const details = [
      diagnostics?.responseStatus ? `status ${diagnostics.responseStatus}` : null,
      diagnostics?.pageTitle ? `title "${diagnostics.pageTitle}"` : null,
      diagnostics?.challengeDetected ? "challenge_detected" : null,
      diagnostics?.accountVerificationDetected ? "account_verification_detected" : null,
      diagnostics?.emptyResultsDetected ? "empty_results_detected" : null
    ]
      .filter(Boolean)
      .join(", ");

    return details ? `${reason} (${details})` : reason;
  }

  private async collectDiagnostics(
    page: Page,
    responseStatus: number | null
  ): Promise<MercadoLivrePageDiagnostics> {
    try {
      const extraction = await this.evaluatePage(page);
      return this.buildDiagnostics(extraction, responseStatus, 0);
    } catch {
      return this.buildFallbackDiagnostics(page.url(), responseStatus);
    }
  }

  private buildFallbackDiagnostics(
    targetUrl: string,
    responseStatus: number | null
  ): MercadoLivrePageDiagnostics {
    return {
      responseStatus,
      finalUrl: targetUrl,
      pageTitle: null,
      bodyTextSnippet: null,
      candidateCount: 0,
      itemCount: 0,
      totalPages: 1,
      nextPageDetected: false,
      challengeDetected: false,
      cloudflareDetected: false,
      cloudfrontDetected: false,
      captchaDetected: false,
      accessDeniedDetected: false,
      accountVerificationDetected: false,
      emptyResultsDetected: false
    };
  }

  private async waitForListingCandidates(page: Page): Promise<void> {
    await this.safeRead(async () => {
      await page.waitForFunction(() => {
        const pageGlobals = globalThis as unknown as {
          document: {
            querySelectorAll: (selector: string) => Iterable<unknown>;
          };
        };

        return Array.from(
          pageGlobals.document.querySelectorAll(
            "li.ui-search-layout__item, div.ui-search-result__wrapper, div[data-testid='result-item']"
          )
        ).some((node) => {
          const element = node as {
            textContent?: string | null;
            innerText?: string | null;
          };
          const text = (element.innerText ?? element.textContent ?? "").replace(/\s+/g, " ").trim();
          return /R\$\s*[\d.]+(?:,\d{2})?/i.test(text);
        });
      }, { timeout: 10_000 });
    });
    await page.waitForTimeout(1_000);
  }

  private async safeRead<T>(callback: () => Promise<T>): Promise<T | null> {
    try {
      return await callback();
    } catch {
      return null;
    }
  }
}

function normalizeVisitedUrl(url: string): string {
  const parsedUrl = new URL(url);
  parsedUrl.hash = "";
  return parsedUrl.toString();
}

function buildMercadoLivreProxySessionId(searchTerm: string, attemptNumber: number): string {
  const normalizedSearchTerm =
    searchTerm
      .toLocaleLowerCase()
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 12) || "mercadolivre";
  return `${normalizedSearchTerm}-${attemptNumber}-${Date.now().toString(36)}`;
}
